import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React, { Suspense } from "react";
import Loading from "./loading";
import { TopNavbar } from "./_components/navbar";
import { TopFooter } from "./_components/footer";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { LogoHeader } from "./_components/logo-header";
import { NavbarBelow } from "./_components/navbar-below";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ISA LABs",
  description: "Generated by create next app",
  authors: [
    {
      name: "KresnaYangAsli",
      url: "https://isa.kresnayangasli.my.id",
    },
    {
      name: "zeroX397",
      url: "https://isa.pengalilla.com",
    },
  ],
  creator:'KresnaYangAsli',
  icons: "https://isa.kresnayangasli.my.id/public/isa_labs.png",
  openGraph: {
    images: "https://isa.kresnayangasli.my.id/public/isa_labs.png"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="night">
      <body className={inter.className}>
        <TopNavbar />
        <LogoHeader />
        <NavbarBelow />
        <div className="divider"></div>
        <Suspense fallback={<Loading />}>
          <main>{children}</main>
        </Suspense>
        <footer className="mt-10">
          <TopFooter />
        </footer>
      </body>
    </html>
  );
}
